apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "rjtch"
  - name: GitHubUser
    value: "rjtch"
  - name: GitHubRepo
    value: "sampletodo"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: 5387-141-2-185-32.eu.ngrok.io
#   If you are using github enterprise, provide a value for GitHubDomain
#  - name: GitHubDomain
#    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
