server:
  port: 8080

spring:
#  profiles:
#    active: docker
  application:
    name: todoService
  data:
    mongodb:
      database: todoapp
      port: 27017
      host: mongodb
  #      username: admin
  #      password: admin
  batch:
    job:
      enabled: false

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
   addresses: rabbitmq:5672
