server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    password: admin
    url: jdbc:postgresql://localhost/notification
#    url: jdbc:postgresql://postgres/notification
    username: admin
  profiles:
    active: default

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  zipkin:
    base-url: http://localhost:9411
#    base-url: http://zipkin:9411

  rabbitmq:
    addresses: localhost:5672
#    addresses: rabbitmq:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
