apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
data:
  secretToken: NzZjNDRjMmJjNDhiMTZhNjg2ZDU4YjkwZTQwOWQ2MDNhMDZiMGI4NzQ0ZmJjZWI4OWNiYWJhMmY5NTA1MjIxOTE2MjRjYTc0NjY3ZTlhMDJmMjZi