server:
  port: 8080

spring:
  profiles:
    active: default
  application:
    name: todoService
  data:
    mongodb:
      database: todoapp
      port: 27017
      host: localhost
#      username: admin
#      password: admin
  batch:
    job:
      enabled: false

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    addresses: localhost:5672
